print("=" * 50)
print("USER INFORMATION INPUT FORM")
print("=" * 50)
print()

full_name = input("Enter your Full Name: ")
age = input("Enter your Age: ")
course = input("Enter your Course: ")
section = input("Enter your Section: ")
favorite_food = input("Enter your Favorite Food: ")

print()
print("=" * 50)
print("INFORMATION SUMMARY")
print("=" * 50)
print()
print("Full Name:      " + full_name)
print("Age:            " + age)
print("Course:         " + course)
print("Section:        " + section)
print("Favorite Food:  " + favorite_food)
print()
print("=" * 50)